### ISSUE TITLE
HTML Validation

### ISSUE THREAD

**Issue by selvianu** [fresher-batch-2021/flightbookingapp-ui#2]
![image](https://user-images.githubusercontent.com/22638364/128355759-a846692e-cddc-4c8f-8fd6-1968ae2a37ad.png)
![image](https://user-images.githubusercontent.com/22638364/128355892-13c7724f-c745-4759-97b1-95d35d186ecf.png)

missing HTML Validation

**Comment by selvianu** [comment]
![image](https://user-images.githubusercontent.com/22638364/128356118-af5670d1-d732-4b6c-8ad4-03f53a17458c.png)
![image](https://user-images.githubusercontent.com/22638364/128356458-51ded1f0-33b6-45fe-8eff-24b2fe61bb27.png)


absence of html attributes
inconsistent naming

**Comment by Rajesh9107** [comment]
I fixed this two issues.
